name: ride_sharing_user_app
description: A ride sharing Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  http: ^1.3.0
  connectivity_plus: ^7.0.0
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.0.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  country_code_picker: ^3.3.0
  dotted_border: ^3.1.0
  percent_indicator: ^4.2.5
  url_launcher: ^6.3.1
  flutter_html: ^3.0.0-beta.2
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.17
  shimmer_animation: ^2.2.2
  file_picker: ^10.0.0
  permission_handler: ^12.0.0
  syncfusion_flutter_datepicker: ^31.1.22
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.2
  flutter_animarker: ^3.2.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  loading_overlay_pro: ^2.1.1
  modal_bottom_sheet: ^3.0.0
  flutter_widget_from_html_core: ^0.17.0
  flutter_typeahead: ^5.2.0
  dotted_line: ^3.2.3
  autocomplete_textfield: ^2.0.1
  flutter_inappwebview: ^6.1.5
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  dart_pusher_channels: ^1.2.3
  flutter_switch: ^0.3.2
  uuid: ^4.5.1
  just_the_tooltip: ^0.0.12
  speech_to_text: ^7.0.0
  app_links: ^6.4.0
  share_plus: ^12.0.0
  video_thumbnail: ^0.5.3
  video_player: ^2.9.5
  chewie: ^1.11.1
  firebase_auth: ^6.1.0
  phone_numbers_parser: ^9.0.3
  sqflite: ^2.3.0
  web_socket_channel: ^2.4.0
  path: ^1.9.0
  supabase_flutter: ^2.10.2
  device_info_plus: ^11.1.0
  google_mobile_ads: ^5.1.0
  youtube_player_flutter: ^9.1.1
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/svg/
    - assets/map/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/font/sf-pro-text-light.ttf
          weight: 300
        - asset: assets/font/sf-pro-text-regular.ttf
          weight: 400
        - asset: assets/font/sf-pro-text-medium.ttf
          weight: 500
        - asset: assets/font/sf-pro-text-semibold.ttf
          weight: 600
        - asset: assets/font/sf-pro-text-bold.ttf
          weight: 700
        - asset: assets/font/sf-pro-text-heavy.ttf
          weight: 900

    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
